name: MLOps Housing CI/CD

on:
  push:
    branches:
      - main

jobs:
  test-suite:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest tests/

  train-and-quantize:
    name: Train & Quantize Model
    runs-on: ubuntu-latest
    needs: test-suite

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train Model
        run: python src/train.py

      - name: Quantize Model
        run: python src/quantize.py

      - name: Upload Model Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: models
          path: |
            models/
            params/

  build-and-test-container:
    name: Build and Test Docker Container
    runs-on: ubuntu-latest
    needs: train-and-quantize

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t mlops-housing:v1 .

      - name: Run Prediction Inside Container
        run: docker run --rm mlops-housing:v1
